---
all:
  children:
    dev:
      hosts:
        dev-cluster: 
          localhost: localhost
          ansible_connection: local
   
    beta:
      hosts:
        beta-cluster:
          localhost: localhost
          ansible_connection: local
          
