name: DigitalAge dev builder & deploy 
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ansible
    steps:
      - uses: actions/checkout@v1
      - run: echo ${{ secrets.MASTER_KEY }}
      - run: echo ${{ secrets.MASTER_KEY }} > .vault_pass.txt
      - run: cat .vault_pass.txt
      - run: sudo apt-get install python3 python3-pip ruby -y 
      - run: sudo pip install --upgrade pip
      - run: sudo pip install ansible
      - run: ansible-playbook playbooks/beta.yml -e context=context

