name: DigitalAge dev builder & deploy 
on:
  push:
    branches:
      - '*'
jobs:
  build:
    runs-on: ubuntu-latest
    # defaults:
    #   run:
    #     working-directory: ansible
    steps:
      - uses: actions/checkout@v1
      - run: |
          echo hola
          echo "🎉 triggered by a ${{ github.event_name }}"
          echo ${{ secrets.myenv.MASTER_KEY }}
      # This preconditions needs to be encapsulated DYR , We need to create our customized base image 
      #- uses: actions/checkout@v1
      #- run: echo "🎉 triggered by a ${{ github.event_name }} digitalAge team event."
      #- run: echo ${{ secrets.MASTER_KEY }}
      # - run: sudo apt-get install python3 python3-pip ruby -y 
      # - run: sudo pip install --upgrade pip
      # - run: sudo pip install ansible
      # - run: ansible-galaxy install -r requirements.yml
      # # This preconditions needs to be encapsulated DYR , We need to create our customized base image
      # - run: ansible-playbook playbooks/builder.yml -t registry-login -v 

#1
